name: build

on: push

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        # with:
        #   vcpkgDirectory: "${{ github.workspace }}/vcpkg"
        #   vcpkgGitCommitId: 9dd12f8d791f6fa4e396adbebc714d51cbee2143
        #   vcpkgJsonGlob: "vcpkg.json"
        #   runVcpkgInstall: true
        #   doNotCache: false

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          configurePreset: "default"
          buildPreset: "release"
          configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE=/home/runner/work/test-ci/test-ci/vcpkg/scripts/buildsystems/vcpkg.cmake']"

      - name: Test
        run: |
          ls -lrth
          cd ${{ github.workspace }}/build
          ./rapidjson_demo

      - name: Print
        run: |
          ls -lrth 969f6665-88a2-4c98-938e-ca9259871fec