name: build

on: push

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.21.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"
          vcpkgGitCommitId: 9dd12f8d791f6fa4e396adbebc714d51cbee2143
          vcpkgJsonGlob: "vcpkg.json"
          runVcpkgInstall: true
          doNotCache: false

      - name: Vcpkg integrate install
        run: ${{ github.workspace }}/vcpkg/vcpkg integrate install

      - name: Build
        uses: lukka/run-cmake@v11
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          configurePreset: "default"
          buildPreset: "release"
          configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE=/home/runner/work/test-ci/test-ci/vcpkg/scripts/buildsystems/vcpkg.cmake']"

      - name: Test print
        run: |
          cd ${{ github.workspace }}/build
          ./rapidjson_demo