name: build zq

on: push

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Print
        run: |
          echo $HOME
          pwd
          echo "Current directory: $(pwd)"
          echo "GitHub workspace: ${{ github.workspace }}"
          echo "GitHub workspace:" $GITHUB_WORKSPACE
          echo "GitHub workspace: ${GITHUB_WORKSPACE}" 
          echo "Contents:"
          ls -lrth

          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          echo "WORK_HOME=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

           ${{ github.workspace }}/vcpkg/vcpkg remove --outdated --recurse

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Cache vcpkg 
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ~/.cache/vcpkg/archives
          key: ubuntu-latest-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: ubuntu-latest-vcpkg-

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"
          vcpkgArguments: "@${{ github.workspace }}/workspace/vcpkg-x64-linux.txt"

      - name: Test
        run: |
          ls -lrth
          cd ${{ env.WORK_HOME }}/build
          ./rapidjson_demo

  # build-on-docker:
  #   runs-on: ubuntu-latest

  #   container:
  #     image: "debian:11"
  #     options: --shm-size=2g

  #   steps:
  #     - name: Install all dependencies
  #       run: |
  #         apt-get update
  #         apt install -y zlib1g zlib1g-dev bzip2 lzma lzma-dev liblzma-dev flex bison
  #         apt install -y build-essential git git-lfs wget libssl-dev curl zip unzip tar pkg-config
  #         apt-get install -y autoconf-archive elfutils jq
  #         apt-get install -y procps findutils grep gawk
  #         apt --fix-broken install
  #         apt-get install -y postgresql postgresql-client libpq-dev

  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         lfs: true
  #         submodules: recursive

  #     - name: Print
  #       run: |
  #         echo $HOME
  #         pwd
  #         echo "Current directory: $(pwd)"
  #         echo "GitHub workspace: ${{ github.workspace }}"
  #         echo "GitHub workspace:" $GITHUB_WORKSPACE
  #         echo "GitHub workspace: ${GITHUB_WORKSPACE}" 
  #         echo "Contents:"
  #         ls -lrth

  #         git config --global --add safe.directory ${GITHUB_WORKSPACE}
  #         echo "WORK_HOME=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

  #     - name: Install CMake
  #       uses: lukka/get-cmake@latest

  #     - name: Run vcpkg
  #       uses: lukka/run-vcpkg@v11

  #     - name: Build 
  #       uses: lukka/run-cmake@v10
  #       with:
  #         cmakeListsTxtPath: "${{ env.WORK_HOME }}/CMakeLists.txt"
  #         configurePreset: "default"
  #         buildPreset: "release"
  #         configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE=${{ env.WORK_HOME }}/vcpkg/scripts/buildsystems/vcpkg.cmake']"

  #     - name: Test
  #       run: |
  #         ls -lrth
  #         cd ${{ env.WORK_HOME }}/build
  #         ./rapidjson_demo


