name: build zq

on: push

jobs:
  build-on-docker:
    runs-on: ubuntu-latest

    container:
      image: "debian:11"
      options: --shm-size=2g

    steps:
      - name: Install all dependencies
        run: |
          apt-get update
          apt install -y git git-lfs unzip curl

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Print
        run: |
          echo $HOME
          pwd
          echo "Current directory: $(pwd)"
          echo "GitHub workspace: ${{ github.workspace }}"
          echo "GitHub workspace:" $GITHUB_WORKSPACE
          echo "GitHub workspace: ${GITHUB_WORKSPACE}" 
          echo "Contents:"
          ls -lrth

          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          echo "WORK_HOME=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Build 
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: "${{ env.WORK_HOME }}/CMakeLists.txt"
          configurePreset: "default"
          buildPreset: "release"
          configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE=${{ env.WORK_HOME }}/vcpkg/scripts/buildsystems/vcpkg.cmake']"

      - name: Test
        run: |
          ls -lrth
          cd ${GITHUB_WORKSPACE}/build
          ./rapidjson_demo


